services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: ./server # Point to NestJS folder!
      dockerfile: Dockerfile
    container_name: server
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/myapp?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./server/src:/usr/src/app/src
      - /usr/src/app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "8080:8080"
    depends_on:
      - app
